---
sudo: false
language: ruby
bundler_args: --without system_tests
before_install: rm Gemfile.lock || true
rvm:
  - 2.1.10
  - 2.3.4
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 4.5.0"
  - PUPPET_VERSION="~> 4.6.0"
  - PUPPET_VERSION="~> 4.7.0"
  - PUPPET_VERSION="~> 4.8.0"
  - PUPPET_VERSION="~> 4.9.0"
  - PUPPET_VERSION="~> 5.0.0"
